services:
    LoyaltyCorp\CoreBundle\ApiPlatform\Pagination\CustomPaginationListener:
        tags:
            - { name: kernel.event_listener, event: kernel.view, priority: 17 }

    LoyaltyCorp\CoreBundle\ApiPlatform\Pagination\SerializerContextBuilder:
        decorates: 'api_platform.serializer.context_builder'
        arguments:
            - '@LoyaltyCorp\CoreBundle\ApiPlatform\Pagination\SerializerContextBuilder.inner'
        autoconfigure: false
