services:
    EonX\CoreBundle\ApiPlatform\Pagination\CustomPaginationListener:
        tags:
            - { name: kernel.event_listener, event: kernel.view, priority: 17 }

    EonX\CoreBundle\ApiPlatform\Pagination\SerializerContextBuilder:
        decorates: 'api_platform.serializer.context_builder'
        arguments:
            - '@EonX\CoreBundle\ApiPlatform\Pagination\SerializerContextBuilder.inner'
        autoconfigure: false
