parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EonX\CoreBundle\Services\Lock\Interfaces\LockServiceInterface:
        class: EonX\CoreBundle\Services\Lock\LockService
